# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/user/application_security/secret_detection/pipeline/configure
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
  - secret-detection
  - test

variables:
  SECRET_DETECTION_ENABLED: 'true'

secret_detection:
  stage: secret-detection
include:
  - template: Security/Secret-Detection.gitlab-ci.yml

rust-test:
  stage: test
  image: rust:1.94.0
  script:
    # - rustup default stable || true
    - apt update
    - apt install -y libclang-dev libimgui-dev
    - cargo test --verbose
  artifacts:
    when: always
    paths:
      - target/
    expire_in: 1 week
  only:
    - branches
    - merge_requests
