use std::{fs, fs::read_dir, path::Path};

fn make_ident(s: &str) -> String {
    let mut id = String::from("ICON_");
    for c in s.chars() {
        match c {
            'A'..='Z' | 'a'..='z' | '0'..='9' => id.push(c.to_ascii_uppercase()),
            _ => id.push('_'),
        }
    }
    // collapse consecutive '_'
    let mut out = String::new();
    let mut prev_underscore = false;
    for ch in id.chars() {
        if ch == '_' {
            if prev_underscore {
                continue;
            }
            prev_underscore = true;
        } else {
            prev_underscore = false;
        }
        out.push(ch);
    }
    out
}

fn main() {
    let assets_dir = Path::new("assets/icons");
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let out_rs = Path::new(&out_dir).join("generated_icons.rs");

    let mut src = String::new();
    src.push_str("// Auto-generated by build.rs\n\n");
    src.push_str("pub mod editor_icons {\n");

    for entry in read_dir(assets_dir).expect("assets_dir does not exist") {
        let path = entry.unwrap().path();
        if path.is_file() {
            if let Some(ext) = path.extension().and_then(|e| e.to_str()) {
                if ext.eq_ignore_ascii_case("dds") {
                    let file_name = path.file_name().unwrap();
                    let rel = file_name.to_string_lossy();

                    let id = make_ident(&rel);
                    src.push_str(&format!("    pub static {}: &[u8] = include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"),\"/{}\"));\n", id, path.display()));
                }
            }
        }
    }

    src.push_str("}\n"); // end module
    fs::write(&out_rs, src).expect("write generated_icons.rs");
    println!("cargo:rerun-if-changed=assets/icons");
}
