use std::{
    collections::HashMap,
    fs::{self, read_dir},
    path::Path,
};

fn icon_ident(s: &str) -> String {
    let mut id = String::from("ICON_");
    for c in s.chars() {
        match c {
            'A'..='Z' | 'a'..='z' | '0'..='9' => id.push(c.to_ascii_uppercase()),
            _ => id.push('_'),
        }
    }
    // collapse consecutive '_'
    let mut out = String::new();
    let mut prev_underscore = false;
    for ch in id.chars() {
        if ch == '_' {
            if prev_underscore {
                continue;
            }
            prev_underscore = true;
        } else {
            prev_underscore = false;
        }
        out.push(ch);
    }
    out
}

fn img_ident(s: &str) -> String {
    let mut id = String::from("IMG_");
    for c in s.chars() {
        match c {
            'A'..='Z' | 'a'..='z' | '0'..='9' => id.push(c.to_ascii_uppercase()),
            _ => id.push('_'),
        }
    }
    // collapse consecutive '_'
    let mut out = String::new();
    let mut prev_underscore = false;
    for ch in id.chars() {
        if ch == '_' {
            if prev_underscore {
                continue;
            }
            prev_underscore = true;
        } else {
            prev_underscore = false;
        }
        out.push(ch);
    }
    out
}

fn main() {
    let icons_dir = Path::new("assets/icons");
    let images_dir = Path::new("assets/images");
    let themes_dir = Path::new("assets/themes");
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let icon_rs = Path::new(&out_dir).join("generated_icons.rs");
    let image_rs = Path::new(&out_dir).join("generated_images.rs");
    let theme_rs = Path::new(&out_dir).join("generated_themes.rs");

    let mut src = String::new();
    src.push_str("// Auto-generated by build.rs\n\n");
    src.push_str("pub mod editor_icons {\n");

    for entry in read_dir(icons_dir).expect("assets_dir does not exist") {
        let path = entry.unwrap().path();
        if path.is_file() {
            if let Some(ext) = path.extension().and_then(|e| e.to_str()) {
                if ext.eq_ignore_ascii_case("dds") {
                    let file_name = path.file_name().unwrap();
                    let rel = file_name.to_string_lossy();

                    let id = icon_ident(&rel);
                    src.push_str(&format!("    pub static {}: &[u8] = include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"),\"/{}\"));\n", id, path.display()));
                }
            }
        }
    }

    src.push_str("}\n"); // end module
    fs::write(&icon_rs, src).expect("write generated_icons.rs");
    println!("cargo:rerun-if-changed=assets/icons");

    let mut src = String::new();
    src.push_str("// Auto-generated by build.rs\n\n");
    src.push_str("pub mod editor_images {\n");

    for entry in read_dir(images_dir).expect("assets_dir does not exist") {
        let path = entry.unwrap().path();
        if path.is_file() {
            if let Some(ext) = path.extension().and_then(|e| e.to_str()) {
                if ext.eq_ignore_ascii_case("dds") {
                    let file_name = path.file_name().unwrap();
                    let rel = file_name.to_string_lossy();

                    let id = img_ident(&rel);
                    src.push_str(&format!("    pub static {}: &[u8] = include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"),\"/{}\"));\n", id, path.display()));
                }
            }
        }
    }

    src.push_str("}\n"); // end module
    fs::write(&image_rs, src).expect("write generated_images.rs");
    println!("cargo:rerun-if-changed=assets/images");

    let mut src = String::new();
    src.push_str("// Auto-generated by build.rs\n\n");

    let rd = read_dir(themes_dir).expect("themes_dir does not exist");

    let mut theme_map: HashMap<String, String> = HashMap::new();
    //let mut theme_count: usize = 0;
    for entry in rd {
        let path = entry.unwrap().path();
        if path.is_file() {
            if let Some(ext) = path.extension().and_then(|e| e.to_str()) {
                if ext.eq_ignore_ascii_case("toml") {
                    let file_name = path.file_name().unwrap();
                    let rel = file_name.to_string_lossy();
                    let rel = rel.trim_end_matches(".toml");

                    let v = format!(
                        "include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"),\"/{}\"))",
                        path.display()
                    );
                    theme_map.insert(rel.to_string(), v);
                }
            }
        }
    }

    src.push_str(&format!(
        "pub static EDITOR_THEMES: [[&str; 2]; {}] = [\n",
        theme_map.len()
    ));
    for (k, v) in theme_map.iter() {
        src.push_str(&format!("    [\"{}\", {}],\n", k, v));
    }

    src.push_str("];\n"); // end module
    fs::write(&theme_rs, src).expect("write generated_themes.rs");
    println!("cargo:rerun-if-changed=assets/themes");
}
