[package]
name = "kradiant-editor"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
kradiant = { path = "../kradiant" }
dear-imgui-rs = "0.10.3"
dear-imgui-glow = { version = "0.10.3", features = ["gl_extensions_support"] }
glow = "0.16"
dear-imgui-winit = "0.10.3"
winit = "0.30.12"
glutin = { git = "https://github.com/rust-windowing/glutin.git", branch = "0.32.x", version = "0.32.3" }
dear-imguizmo = "0.10.3"
raw-window-handle = "0.6.2"
glutin-winit = { git = "https://github.com/rust-windowing/glutin.git", branch = "0.32.x", version = "0.5.0" }
rfd = "0.17.2"
glam = { version = "0.32.1", features = ["bytemuck"] }
#bytemuck = { version = "1.25.0", features = ["derive"] }
rust-ini = { version = "0.21.3", features = ["inline-comment"] }
bytemuck = { version = "1.25.0", features = ["derive"] }
toml = "1.0.7"
serde = { version = "1.0.228", features = ["derive"] }
#image = { version = "0.25.10", features = ["dds"], default-features = false }
