[package]
name = "kradiant"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0"
log = "0.4"
image = { version = "0.25.10", default-features = false, features = ["dds", "jpeg", "tga"] }
zip = { version = "8.2.0", default-features = false, features = ["deflate"] }
glow = "0.16"
glam = { version = "0.32.1", features = ["bytemuck"] }
bytemuck = { version = "1.25.0", features = ["derive"] }
toml = "1.0.7"
serde = { version = "1.0.228", features = ["derive"] }
num-traits = "0.2.19"
strum_macros = "0.28.0"
strum = "0.28.0"
