[package]
name = "kradiant"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib", "cdylib", "staticlib"]

[dependencies]
thiserror = "2.0"
log.workspace = true
image = { version = "0.25.10", default-features = false, features = ["dds", "jpeg", "tga"] }
zip = { version = "8.2.0", default-features = false, features = ["deflate"] }
glow.workspace = true
glam = { workspace = true, features = ["bytemuck"] }
bytemuck = { workspace = true, features = ["derive"] }
toml.workspace = true
serde = { workspace = true, features = ["derive"] }
num-traits.workspace = true
strum_macros.workspace = true
strum.workspace = true
rayon.workspace = true
smallvec = "1.16.1"
