/* This file is autogenerated by cbindgen. Do not edit. */

#ifndef KRADIANT_H
#define KRADIANT_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Asset database for a game content directory.
 *
 * - Prefers loose files on disk.
 * - Falls back to `.pk3` archives found directly under `<maindir>`.
 * - Indexes `.pk3` contents once at startup for fast existence checks and resolution.
 */
typedef struct KR_AssetDb KR_AssetDb;

typedef struct KR_Brush KR_Brush;

typedef struct KR_EditorState KR_EditorState;

/**
 * Entity (worldspawn or any other brush collection with key/value properties).
 */
typedef struct KR_Entity KR_Entity;

/**
 * Top‑level map structure, mirroring a complete `.map` file.
 */
typedef struct KR_Map KR_Map;

typedef struct KR_PickMask KR_PickMask;

typedef struct KR_ShaderDb KR_ShaderDb;

typedef struct KR_Vec3 {
  float x;
  float y;
  float z;
} KR_Vec3;
#define KR_Vec3_ZERO (KR_Vec3){ .x = 0.0, .y = 0.0, .z = 0.0 }

typedef struct KR_TextureImage {
  uint32_t width;
  uint32_t height;
  uint8_t *data;
} KR_TextureImage;

typedef struct KR_TexVertex {
  float pos[3];
  float normal[3];
  float uv[2];
} KR_TexVertex;







/**
 * Create a new EditorState.
 * Must be freed with kr_editor_free.
 */
struct KR_EditorState *kr_editor_new(void);

/**
 * Free an EditorState.
 */
void kr_editor_free(struct KR_EditorState *ptr);

/**
 * Load a map into the editor.
 * Returns true on success, false on failure.
 */
bool kr_editor_load_map(struct KR_EditorState *ptr, const char *path);

/**
 * Save the current map.
 * Returns true on success, false on failure.
 */
bool kr_editor_save_map(struct KR_EditorState *ptr, const char *path);

/**
 * Get the version of the library.
 * The returned string is statically allocated and should NOT be freed.
 */
const char *kr_get_version(void);

/**
 * Clear the current selection.
 */
void kr_editor_clear_selection(struct KR_EditorState *ptr);

/**
 * Toggle face editing mode.
 */
void kr_editor_set_edit_faces(struct KR_EditorState *ptr, bool enabled);

/**
 * Toggle vertex editing mode.
 */
void kr_editor_set_edit_vertices(struct KR_EditorState *ptr, bool enabled);

/**
 * Perform undo. Returns true if something was undone.
 */
bool kr_editor_undo(struct KR_EditorState *ptr);

/**
 * Perform redo. Returns true if something was redone.
 */
bool kr_editor_redo(struct KR_EditorState *ptr);

/**
 * Get the number of entities in the current map.
 */
int32_t kr_editor_get_entity_count(struct KR_EditorState *ptr);

/**
 * Get a property value of an entity by key.
 * The returned string MUST be freed with kr_free_string.
 */
char *kr_editor_get_entity_property(struct KR_EditorState *ptr,
                                    int32_t entity_idx,
                                    const char *key);

/**
 * Free a string returned by the library.
 */
void kr_free_string(char *ptr);

/**
 * Select a brush by entity and brush index.
 */
void kr_editor_select_brush(struct KR_EditorState *ptr, int32_t entity_idx, int32_t brush_idx);

/**
 * Translate the current selection.
 */
bool kr_editor_translate_selection(struct KR_EditorState *ptr, struct KR_Vec3 delta);

int32_t kr_map_count_brushes(const struct KR_Map *map_ptr);

struct KR_Vec3 kr_compute_normal(struct KR_Vec3 p1, struct KR_Vec3 p2, struct KR_Vec3 p3);

struct KR_Map *kr_editor_get_map_ptr(struct KR_EditorState *ptr);

struct KR_AssetDb *kr_asset_db_new(const char *maindir);

void kr_asset_db_free(struct KR_AssetDb *ptr);

struct KR_TextureImage *kr_asset_db_load_texture(struct KR_AssetDb *ptr, const char *material);

void kr_texture_image_free(struct KR_TextureImage *ptr);

int32_t kr_brush_get_face_count(const struct KR_Brush *brush_ptr);

char *kr_brush_get_face_texture(const struct KR_Brush *brush_ptr, int32_t face_idx);

bool kr_editor_get_grid_snap(const struct KR_EditorState *ptr);

void kr_editor_set_grid_snap(struct KR_EditorState *ptr, bool enabled);

void kr_editor_get_view2d_pan(const struct KR_EditorState *ptr, float *x, float *y);

void kr_editor_set_view2d_pan(struct KR_EditorState *ptr, float x, float y);

struct KR_Vec3 kr_brush_get_face_plane_point(const struct KR_Brush *brush_ptr,
                                             int32_t face_idx,
                                             int32_t point_idx);

struct KR_Entity *kr_map_get_entity(struct KR_Map *map_ptr, int32_t idx);

int32_t kr_entity_get_brush_count(const struct KR_Entity *ent_ptr);

struct KR_Brush *kr_entity_get_brush(struct KR_Entity *ent_ptr, int32_t idx);

struct KR_ShaderDb *kr_shader_db_load(const char *main_dir);

void kr_shader_db_free(struct KR_ShaderDb *ptr);

void kr_geom_update_brush_plane(struct KR_Brush *brush_ptr,
                                int32_t plane_idx,
                                struct KR_Vec3 p1,
                                struct KR_Vec3 p2,
                                struct KR_Vec3 p3);

bool kr_edit_pick_brush_by_ray(struct KR_Map *map_ptr,
                               struct KR_Vec3 ray_origin,
                               struct KR_Vec3 ray_dir,
                               int32_t *out_ent,
                               int32_t *out_brush);

void kr_tex_q3_axes_from_normal(struct KR_Vec3 normal, struct KR_Vec3 *s, struct KR_Vec3 *t);

void kr_tex_rotate_axes(struct KR_Vec3 s,
                        struct KR_Vec3 t,
                        float angle_rad,
                        struct KR_Vec3 *rs,
                        struct KR_Vec3 *rt);

int32_t kr_brush_get_polygon_count(struct KR_Brush *brush_ptr);

bool kr_brush_get_polygon_data(struct KR_Brush *brush_ptr,
                               int32_t poly_idx,
                               int32_t *out_vertex_count,
                               struct KR_Vec3 *out_vertices,
                               int32_t *out_index_count,
                               uint32_t *out_indices);

void kr_editor_get_view3d_cam(const struct KR_EditorState *ptr,
                              struct KR_Vec3 *pos,
                              struct KR_Vec3 *angles,
                              float *zoom);

void kr_editor_set_view3d_cam(struct KR_EditorState *ptr,
                              struct KR_Vec3 pos,
                              struct KR_Vec3 angles,
                              float zoom);

char *kr_editor_get_new_prop_key(const struct KR_EditorState *ptr);

void kr_editor_set_new_prop_key(struct KR_EditorState *ptr, const char *val);

char *kr_editor_get_new_prop_val(const struct KR_EditorState *ptr);

void kr_editor_set_new_prop_val(struct KR_EditorState *ptr, const char *val);

bool kr_render_gen_grid(float pan_x,
                        float pan_y,
                        float zoom,
                        float width,
                        float height,
                        float minor_step,
                        int32_t *out_vertex_count,
                        struct KR_Vec3 *out_vertices,
                        bool is_major);

int32_t kr_brush_get_wireframe_count(struct KR_Brush *brush_ptr);

bool kr_brush_get_wireframe_data(struct KR_Brush *brush_ptr, struct KR_Vec3 *out_vertices);

bool kr_patch_get_tessellation_counts(struct KR_Brush *brush_ptr,
                                      int32_t *out_vertex_count,
                                      int32_t *out_index_count);

bool kr_patch_get_tessellation_data(struct KR_Brush *brush_ptr,
                                    struct KR_TexVertex *out_vertices,
                                    uint32_t *out_indices);

void kr_face_uv(const struct KR_Brush *brush_ptr,
                int32_t face_idx,
                struct KR_Vec3 point,
                float tex_w,
                float tex_h,
                float *out_uv);

struct KR_Vec3 kr_face_plane_normal(const struct KR_Brush *brush_ptr, int32_t face_idx);

#endif  /* KRADIANT_H */
