# Comfortable Dark Cyan style by SouthCraftX from ImThemes
alpha = 1.0
disabledAlpha = 1.0
windowPadding = [20.0, 20.0]
windowRounding = 11.5
windowBorderSize = 0.0
windowMinSize = [20.0, 20.0]
windowTitleAlign = [0.5, 0.5]
windowMenuButtonPosition = "None"
childRounding = 20.0
childBorderSize = 1.0
popupRounding = 17.4
popupBorderSize = 1.0
framePadding = [20.0, 3.4]
frameRounding = 11.9
frameBorderSize = 0.0
itemSpacing = [8.9, 13.4]
itemInnerSpacing = [7.1, 1.8]
cellPadding = [12.1, 9.2]
indentSpacing = 0.0
columnsMinSpacing = 8.7
scrollbarSize = 11.6
scrollbarRounding = 15.9
grabMinSize = 3.7
grabRounding = 20.0
tabRounding = 9.8
tabBorderSize = 0.0
tabMinWidthForCloseButton = 0.0
colorButtonPosition = "Right"
buttonTextAlign = [0.5, 0.5]
selectableTextAlign = [0.0, 0.0]

[colors]
Text = "rgba(255, 255, 255, 1.0)"
TextDisabled = "rgba(70, 81, 115, 1.0)"
WindowBg = "rgba(20, 22, 26, 1.0)"
ChildBg = "rgba(24, 26, 30, 1.0)"
PopupBg = "rgba(20, 22, 26, 1.0)"
Border = "rgba(40, 43, 49, 1.0)"
BorderShadow = "rgba(20, 22, 26, 1.0)"
FrameBg = "rgba(29, 32, 39, 1.0)"
FrameBgHovered = "rgba(40, 43, 49, 1.0)"
FrameBgActive = "rgba(40, 43, 49, 1.0)"
TitleBg = "rgba(12, 14, 18, 1.0)"
TitleBgActive = "rgba(12, 14, 18, 1.0)"
TitleBgCollapsed = "rgba(20, 22, 26, 1.0)"
MenuBarBg = "rgba(25, 27, 31, 1.0)"
ScrollbarBg = "rgba(12, 14, 18, 1.0)"
ScrollbarGrab = "rgba(30, 34, 38, 1.0)"
ScrollbarGrabHovered = "rgba(40, 43, 49, 1.0)"
ScrollbarGrabActive = "rgba(30, 34, 38, 1.0)"
CheckMark = "rgba(8, 242, 215, 1.0)"
SliderGrab = "rgba(8, 242, 215, 1.0)"
SliderGrabActive = "rgba(153, 246, 8, 1.0)"
Button = "rgba(30, 34, 38, 1.0)"
ButtonHovered = "rgba(46, 48, 50, 1.0)"
ButtonActive = "rgba(39, 39, 39, 1.0)"
Header = "rgba(36, 42, 53, 1.0)"
HeaderHovered = "rgba(27, 27, 27, 1.0)"
HeaderActive = "rgba(20, 22, 26, 1.0)"
Separator = "rgba(33, 38, 49, 1.0)"
SeparatorHovered = "rgba(40, 47, 64, 1.0)"
SeparatorActive = "rgba(40, 47, 64, 1.0)"
ResizeGrip = "rgba(37, 37, 37, 1.0)"
ResizeGripHovered = "rgba(8, 242, 215, 1.0)"
ResizeGripActive = "rgba(255, 255, 255, 1.0)"
Tab = "rgba(20, 22, 26, 1.0)"
TabHovered = "rgba(30, 34, 38, 1.0)"
TabActive = "rgba(30, 34, 38, 1.0)"
TabUnfocused = "rgba(20, 22, 26, 1.0)"
TabUnfocusedActive = "rgba(32, 70, 146, 1.0)"
PlotLines = "rgba(133, 153, 179, 1.0)"
PlotLinesHovered = "rgba(10, 250, 250, 1.0)"
PlotHistogram = "rgba(8, 242, 215, 1.0)"
PlotHistogramHovered = "rgba(40, 47, 64, 1.0)"
TableHeaderBg = "rgba(12, 14, 18, 1.0)"
TableBorderStrong = "rgba(12, 14, 18, 1.0)"
TableBorderLight = "rgba(0, 0, 0, 1.0)"
TableRowBg = "rgba(30, 34, 38, 1.0)"
TableRowBgAlt = "rgba(25, 27, 31, 1.0)"
TextSelectedBg = "rgba(239, 239, 239, 1.0)"
DragDropTarget = "rgba(127, 131, 255, 1.0)"
NavHighlight = "rgba(68, 74, 255, 1.0)"
NavWindowingHighlight = "rgba(127, 131, 255, 1.0)"
NavWindowingDimBg = "rgba(50, 45, 139, 0.5019608)"
ModalWindowDimBg = "rgba(50, 45, 139, 0.5019608)"
