# Eggplant style by yo-ru from ImThemes
alpha = 1.0
disabledAlpha = 0.6
windowPadding = [10.0, 10.0]
windowRounding = 10.0
windowBorderSize = 1.0
windowMinSize = [20.0, 32.0]
windowTitleAlign = [0.5, 0.5]
windowMenuButtonPosition = "None"
childRounding = 10.0
childBorderSize = 1.0
popupRounding = 10.0
popupBorderSize = 1.0
framePadding = [15.0, 5.8]
frameRounding = 6.0
frameBorderSize = 0.0
itemSpacing = [4.0, 6.0]
itemInnerSpacing = [10.0, 4.0]
cellPadding = [4.0, 4.0]
indentSpacing = 20.0
columnsMinSpacing = 4.0
scrollbarSize = 20.0
scrollbarRounding = 10.0
grabMinSize = 10.0
grabRounding = 10.0
tabRounding = 6.0
tabBorderSize = 0.0
tabMinWidthForCloseButton = 0.0
colorButtonPosition = "Right"
buttonTextAlign = [0.5, 0.5]
selectableTextAlign = [0.0, 0.0]

[colors]
Text = "rgba(242, 242, 242, 1.0)"
TextDisabled = "rgba(242, 242, 242, 0.34509805)"
WindowBg = "rgba(122, 89, 117, 1.0)"
ChildBg = "rgba(122, 89, 117, 1.0)"
PopupBg = "rgba(122, 89, 117, 1.0)"
Border = "rgba(41, 28, 45, 1.0)"
BorderShadow = "rgba(0, 0, 0, 0.0)"
FrameBg = "rgba(41, 28, 45, 1.0)"
FrameBgHovered = "rgba(41, 28, 45, 1.0)"
FrameBgActive = "rgba(41, 28, 45, 0.8197425)"
TitleBg = "rgba(41, 28, 45, 1.0)"
TitleBgActive = "rgba(41, 28, 45, 1.0)"
TitleBgCollapsed = "rgba(41, 28, 45, 1.0)"
MenuBarBg = "rgba(41, 28, 45, 1.0)"
ScrollbarBg = "rgba(41, 28, 45, 1.0)"
ScrollbarGrab = "rgba(154, 107, 147, 0.3019608)"
ScrollbarGrabHovered = "rgba(154, 107, 147, 0.4)"
ScrollbarGrabActive = "rgba(154, 107, 147, 0.6)"
CheckMark = "rgba(154, 107, 147, 1.0)"
SliderGrab = "rgba(154, 107, 147, 0.3019608)"
SliderGrabActive = "rgba(154, 107, 147, 0.6)"
Button = "rgba(41, 28, 45, 1.0)"
ButtonHovered = "rgba(41, 28, 45, 0.4)"
ButtonActive = "rgba(41, 28, 45, 0.6)"
Header = "rgba(41, 28, 45, 1.0)"
HeaderHovered = "rgba(41, 28, 45, 1.0)"
HeaderActive = "rgba(41, 28, 45, 1.0)"
Separator = "rgba(41, 28, 45, 1.0)"
SeparatorHovered = "rgba(41, 28, 45, 1.0)"
SeparatorActive = "rgba(41, 28, 45, 1.0)"
ResizeGrip = "rgba(41, 28, 45, 0.4549356)"
ResizeGripHovered = "rgba(41, 28, 45, 0.7811159)"
ResizeGripActive = "rgba(41, 28, 45, 0.9019608)"
Tab = "rgba(41, 28, 45, 1.0)"
TabHovered = "rgba(41, 28, 45, 0.8)"
TabActive = "rgba(41, 28, 45, 0.84313726)"
TabUnfocused = "rgba(41, 28, 45, 0.81960785)"
TabUnfocusedActive = "rgba(41, 28, 45, 0.8352941)"
PlotLines = "rgba(242, 242, 242, 1.0)"
PlotLinesHovered = "rgba(122, 89, 117, 1.0)"
PlotHistogram = "rgba(155, 109, 148, 1.0)"
PlotHistogramHovered = "rgba(155, 109, 148, 0.639485)"
TableHeaderBg = "rgba(41, 28, 45, 1.0)"
TableBorderStrong = "rgba(41, 28, 45, 1.0)"
TableBorderLight = "rgba(41, 28, 45, 1.0)"
TableRowBg = "rgba(0, 0, 0, 0.0)"
TableRowBgAlt = "rgba(255, 255, 255, 0.01716739)"
TextSelectedBg = "rgba(154, 107, 147, 0.6)"
DragDropTarget = "rgba(155, 109, 148, 1.0)"
NavHighlight = "rgba(41, 28, 45, 0.8)"
NavWindowingHighlight = "rgba(41, 28, 45, 0.7019608)"
NavWindowingDimBg = "rgba(41, 28, 45, 0.2)"
ModalWindowDimBg = "rgba(41, 28, 45, 0.34901962)"
