# Everforest style by DestroyerDarkNess from ImThemes
alpha = 1.0
disabledAlpha = 0.6
windowPadding = [6.0, 3.0]
windowRounding = 6.0
windowBorderSize = 1.0
windowMinSize = [32.0, 32.0]
windowTitleAlign = [0.5, 0.5]
windowMenuButtonPosition = "Left"
childRounding = 0.0
childBorderSize = 1.0
popupRounding = 0.0
popupBorderSize = 1.0
framePadding = [5.0, 5.0]
frameRounding = 3.0
frameBorderSize = 1.0
itemSpacing = [8.0, 4.0]
itemInnerSpacing = [4.0, 4.0]
cellPadding = [4.0, 2.0]
indentSpacing = 21.0
columnsMinSpacing = 6.0
scrollbarSize = 13.0
scrollbarRounding = 16.0
grabMinSize = 20.0
grabRounding = 2.0
tabRounding = 4.0
tabBorderSize = 1.0
tabMinWidthForCloseButton = 0.0
colorButtonPosition = "Right"
buttonTextAlign = [0.5, 0.5]
selectableTextAlign = [0.0, 0.0]

[colors]
Text = "rgba(223, 222, 214, 1.0)"
TextDisabled = "rgba(149, 146, 133, 1.0)"
WindowBg = "rgba(60, 56, 54, 1.0)"
ChildBg = "rgba(60, 56, 54, 1.0)"
PopupBg = "rgba(60, 56, 54, 1.0)"
Border = "rgba(80, 73, 69, 1.0)"
BorderShadow = "rgba(60, 56, 54, 0.0)"
FrameBg = "rgba(80, 73, 69, 1.0)"
FrameBgHovered = "rgba(102, 92, 84, 1.0)"
FrameBgActive = "rgba(124, 111, 100, 1.0)"
TitleBg = "rgba(60, 56, 54, 1.0)"
TitleBgActive = "rgba(80, 73, 69, 1.0)"
TitleBgCollapsed = "rgba(60, 56, 54, 1.0)"
MenuBarBg = "rgba(80, 73, 69, 1.0)"
ScrollbarBg = "rgba(60, 56, 54, 1.0)"
ScrollbarGrab = "rgba(124, 111, 100, 1.0)"
ScrollbarGrabHovered = "rgba(102, 92, 84, 1.0)"
ScrollbarGrabActive = "rgba(80, 73, 69, 1.0)"
CheckMark = "rgba(152, 151, 26, 1.0)"
SliderGrab = "rgba(152, 151, 26, 1.0)"
SliderGrabActive = "rgba(189, 183, 107, 1.0)"
Button = "rgba(102, 92, 84, 1.0)"
ButtonHovered = "rgba(124, 111, 100, 1.0)"
ButtonActive = "rgba(189, 183, 107, 1.0)"
Header = "rgba(102, 92, 84, 1.0)"
HeaderHovered = "rgba(124, 111, 100, 1.0)"
HeaderActive = "rgba(189, 183, 107, 1.0)"
Separator = "rgba(189, 183, 107, 1.0)"
SeparatorHovered = "rgba(124, 111, 100, 1.0)"
SeparatorActive = "rgba(189, 183, 107, 1.0)"
ResizeGrip = "rgba(102, 92, 84, 1.0)"
ResizeGripHovered = "rgba(124, 111, 100, 1.0)"
ResizeGripActive = "rgba(189, 183, 107, 1.0)"
Tab = "rgba(80, 73, 69, 1.0)"
TabHovered = "rgba(102, 92, 84, 1.0)"
TabActive = "rgba(124, 111, 100, 1.0)"
TabUnfocused = "rgba(60, 56, 54, 0.972549)"
TabUnfocusedActive = "rgba(80, 73, 69, 1.0)"
PlotLines = "rgba(189, 183, 107, 1.0)"
PlotLinesHovered = "rgba(214, 191, 102, 1.0)"
PlotHistogram = "rgba(189, 183, 107, 1.0)"
PlotHistogramHovered = "rgba(214, 191, 102, 1.0)"
TableHeaderBg = "rgba(214, 191, 102, 0.60944206)"
TableBorderStrong = "rgba(79, 79, 89, 1.0)"
TableBorderLight = "rgba(58, 58, 63, 1.0)"
TableRowBg = "rgba(0, 0, 0, 0.0)"
TableRowBgAlt = "rgba(255, 255, 255, 0.06)"
TextSelectedBg = "rgba(214, 191, 102, 0.43137255)"
DragDropTarget = "rgba(214, 191, 102, 0.9019608)"
NavHighlight = "rgba(60, 56, 54, 1.0)"
NavWindowingHighlight = "rgba(255, 255, 255, 0.7)"
NavWindowingDimBg = "rgba(204, 204, 204, 0.2)"
ModalWindowDimBg = "rgba(204, 204, 204, 0.35)"

[editor]
windowClear = "rgba(60, 56, 54, 1.0)"
view2dBg = "rgba(60, 56, 54, 1.0)"
view2dGridMajor = "rgba(80, 73, 69, 1.0)"
view2dGridMinor = "rgba(70, 64, 60, 1.0)"
view2dAxisX = "rgba(152, 151, 26, 1.0)"
view2dAxisY = "rgba(214, 191, 102, 1.0)"
view2dGeometry = "rgba(223, 222, 214, 1.0)"
consoleInfo = "rgba(223, 222, 214, 1.0)"
consoleWarn = "rgba(214, 191, 102, 1.0)"
consoleError = "rgba(231, 76, 60, 1.0)"
hudText = "rgba(223, 222, 214, 1.0)"
hudTextDim = "rgba(149, 146, 133, 1.0)"
