# Kazam's Cherry style from ImThemes
alpha = 1.0
disabledAlpha = 0.6
windowPadding = [6.0, 3.0]
windowRounding = 0.0
windowBorderSize = 1.0
windowMinSize = [32.0, 32.0]
windowTitleAlign = [0.5, 0.5]
windowMenuButtonPosition = "Left"
childRounding = 0.0
childBorderSize = 1.0
popupRounding = 0.0
popupBorderSize = 1.0
framePadding = [5.0, 5.0]
frameRounding = 1.0
frameBorderSize = 0.0
itemSpacing = [7.0, 1.0]
itemInnerSpacing = [1.0, 1.0]
cellPadding = [4.0, 4.0]
indentSpacing = 6.0
columnsMinSpacing = 6.0
scrollbarSize = 13.0
scrollbarRounding = 16.0
grabMinSize = 20.0
grabRounding = 2.0
tabRounding = 2.0
tabBorderSize = 0.0
tabMinWidthForCloseButton = 0.0
colorButtonPosition = "Right"
buttonTextAlign = [0.5, 0.5]
selectableTextAlign = [0.0, 0.0]

[colors]
Text = "rgba(219, 237, 226, 0.88)"
TextDisabled = "rgba(219, 237, 226, 0.28)"
WindowBg = "rgba(33, 35, 43, 1.0)"
ChildBg = "rgba(0, 0, 0, 0.0)"
PopupBg = "rgba(51, 56, 68, 0.9)"
Border = "rgba(137, 122, 65, 0.162)"
BorderShadow = "rgba(0, 0, 0, 0.0)"
FrameBg = "rgba(51, 56, 68, 1.0)"
FrameBgHovered = "rgba(116, 50, 76, 0.78)"
FrameBgActive = "rgba(116, 50, 76, 1.0)"
TitleBg = "rgba(59, 51, 69, 1.0)"
TitleBgActive = "rgba(128, 19, 65, 1.0)"
TitleBgCollapsed = "rgba(51, 56, 68, 0.75)"
MenuBarBg = "rgba(51, 56, 68, 0.47)"
ScrollbarBg = "rgba(51, 56, 68, 1.0)"
ScrollbarGrab = "rgba(22, 38, 40, 1.0)"
ScrollbarGrabHovered = "rgba(116, 50, 76, 0.78)"
ScrollbarGrabActive = "rgba(116, 50, 76, 1.0)"
CheckMark = "rgba(181, 56, 68, 1.0)"
SliderGrab = "rgba(119, 196, 211, 0.14)"
SliderGrabActive = "rgba(181, 56, 68, 1.0)"
Button = "rgba(119, 196, 211, 0.14)"
ButtonHovered = "rgba(116, 50, 76, 0.86)"
ButtonActive = "rgba(211, 78, 92, 0.9)"
Header = "rgba(116, 50, 76, 0.76)"
HeaderHovered = "rgba(116, 50, 76, 0.86)"
HeaderActive = "rgba(128, 19, 65, 1.0)"
Separator = "rgba(109, 109, 127, 0.5)"
SeparatorHovered = "rgba(132, 56, 86, 0.88412017)"
SeparatorActive = "rgba(116, 50, 76, 1.0)"
ResizeGrip = "rgba(119, 196, 211, 0.04)"
ResizeGripHovered = "rgba(116, 50, 76, 0.78)"
ResizeGripActive = "rgba(116, 50, 76, 1.0)"
Tab = "rgba(181, 56, 68, 0.82832617)"
TabHovered = "rgba(181, 56, 68, 1.0)"
TabActive = "rgba(181, 56, 68, 1.0)"
TabUnfocused = "rgba(17, 26, 37, 0.9724)"
TabUnfocusedActive = "rgba(116, 50, 76, 1.0)"
PlotLines = "rgba(219, 237, 226, 0.63)"
PlotLinesHovered = "rgba(116, 50, 76, 1.0)"
PlotHistogram = "rgba(219, 237, 226, 0.63)"
PlotHistogramHovered = "rgba(116, 50, 76, 1.0)"
TableHeaderBg = "rgba(48, 48, 51, 1.0)"
TableBorderStrong = "rgba(79, 79, 89, 1.0)"
TableBorderLight = "rgba(58, 58, 63, 1.0)"
TableRowBg = "rgba(0, 0, 0, 0.0)"
TableRowBgAlt = "rgba(255, 255, 255, 0.06)"
TextSelectedBg = "rgba(116, 50, 76, 0.43)"
DragDropTarget = "rgba(255, 255, 0, 0.9)"
NavHighlight = "rgba(66, 150, 249, 1.0)"
NavWindowingHighlight = "rgba(255, 255, 255, 0.7)"
NavWindowingDimBg = "rgba(204, 204, 204, 0.2)"
ModalWindowDimBg = "rgba(204, 204, 204, 0.35)"

[editor]
windowClear = "rgba(33, 35, 43, 1.0)"
view2dBg = "rgba(51, 56, 68, 1.0)"
view2dGridMajor = "rgba(76, 84, 102, 1.0)"
view2dGridMinor = "rgba(63, 70, 85, 1.0)"
view2dAxisX = "rgba(181, 56, 68, 1.0)"
view2dAxisY = "rgba(119, 196, 211, 1.0)"
view2dGeometry = "rgba(219, 237, 226, 1.0)"
consoleInfo = "rgba(219, 237, 226, 0.88)"
consoleWarn = "rgba(255, 209, 102, 1.0)"
consoleError = "rgba(255, 110, 110, 1.0)"
hudText = "rgba(219, 237, 226, 0.88)"
hudTextDim = "rgba(219, 237, 226, 0.55)"
