# Purple Comfy style by RegularLunar from ImThemes
alpha = 1.0
disabledAlpha = 0.1
windowPadding = [8.0, 8.0]
windowRounding = 10.0
windowBorderSize = 0.0
windowMinSize = [30.0, 30.0]
windowTitleAlign = [0.5, 0.5]
windowMenuButtonPosition = "Right"
childRounding = 5.0
childBorderSize = 1.0
popupRounding = 10.0
popupBorderSize = 0.0
framePadding = [5.0, 3.5]
frameRounding = 5.0
frameBorderSize = 0.0
itemSpacing = [5.0, 4.0]
itemInnerSpacing = [5.0, 5.0]
cellPadding = [4.0, 2.0]
indentSpacing = 5.0
columnsMinSpacing = 5.0
scrollbarSize = 15.0
scrollbarRounding = 9.0
grabMinSize = 15.0
grabRounding = 5.0
tabRounding = 5.0
tabBorderSize = 0.0
tabMinWidthForCloseButton = 0.0
colorButtonPosition = "Right"
buttonTextAlign = [0.5, 0.5]
selectableTextAlign = [0.0, 0.0]

[colors]
Text = "rgba(255, 255, 255, 1.0)"
TextDisabled = "rgba(255, 255, 255, 0.360515)"
WindowBg = "rgba(25, 25, 25, 1.0)"
ChildBg = "rgba(255, 0, 0, 0.0)"
PopupBg = "rgba(25, 25, 25, 1.0)"
Border = "rgba(128, 77, 255, 0.54901963)"
BorderShadow = "rgba(0, 0, 0, 0.0)"
FrameBg = "rgba(40, 40, 40, 1.0)"
FrameBgHovered = "rgba(97, 108, 146, 0.54901963)"
FrameBgActive = "rgba(128, 77, 255, 0.54901963)"
TitleBg = "rgba(25, 25, 25, 1.0)"
TitleBgActive = "rgba(25, 25, 25, 1.0)"
TitleBgCollapsed = "rgba(66, 66, 66, 0.0)"
MenuBarBg = "rgba(0, 0, 0, 0.0)"
ScrollbarBg = "rgba(40, 40, 40, 0.0)"
ScrollbarGrab = "rgba(40, 40, 40, 1.0)"
ScrollbarGrabHovered = "rgba(60, 60, 60, 1.0)"
ScrollbarGrabActive = "rgba(75, 75, 75, 1.0)"
CheckMark = "rgba(128, 77, 255, 0.54901963)"
SliderGrab = "rgba(128, 77, 255, 0.54901963)"
SliderGrabActive = "rgba(128, 77, 255, 0.54901963)"
Button = "rgba(128, 77, 255, 0.54901963)"
ButtonHovered = "rgba(128, 77, 255, 0.54901963)"
ButtonActive = "rgba(141, 96, 255, 0.88)"
Header = "rgba(128, 77, 255, 0.54901963)"
HeaderHovered = "rgba(128, 77, 255, 0.54901963)"
HeaderActive = "rgba(128, 77, 255, 0.54901963)"
Separator = "rgba(128, 77, 255, 0.54901963)"
SeparatorHovered = "rgba(128, 77, 255, 0.54901963)"
SeparatorActive = "rgba(128, 77, 255, 0.54901963)"
ResizeGrip = "rgba(128, 77, 255, 0.54901963)"
ResizeGripHovered = "rgba(128, 77, 255, 0.54901963)"
ResizeGripActive = "rgba(128, 77, 255, 0.54901963)"
Tab = "rgba(128, 77, 255, 0.54901963)"
TabHovered = "rgba(128, 77, 255, 0.54901963)"
TabActive = "rgba(128, 77, 255, 0.54901963)"
TabUnfocused = "rgba(0, 115, 255, 0.0)"
TabUnfocusedActive = "rgba(34, 66, 108, 0.0)"
PlotLines = "rgba(75, 75, 75, 1.0)"
PlotLinesHovered = "rgba(128, 77, 255, 0.54901963)"
PlotHistogram = "rgba(128, 77, 255, 0.54901963)"
PlotHistogramHovered = "rgba(188, 177, 226, 0.54901963)"
TableHeaderBg = "rgba(48, 48, 51, 1.0)"
TableBorderStrong = "rgba(128, 77, 255, 0.54901963)"
TableBorderLight = "rgba(128, 77, 255, 0.2901961)"
TableRowBg = "rgba(0, 0, 0, 0.0)"
TableRowBgAlt = "rgba(255, 255, 255, 0.03433478)"
TextSelectedBg = "rgba(128, 77, 255, 0.54901963)"
DragDropTarget = "rgba(255, 255, 0, 0.9)"
NavHighlight = "rgba(0, 0, 0, 1.0)"
NavWindowingHighlight = "rgba(255, 255, 255, 0.7)"
NavWindowingDimBg = "rgba(204, 204, 204, 0.2)"
ModalWindowDimBg = "rgba(204, 204, 204, 0.35)"

[editor]
windowClear = "rgba(25, 25, 25, 1.0)"
view2dBg = "rgba(25, 25, 25, 1.0)"
view2dGridMajor = "rgba(40, 40, 40, 1.0)"
view2dGridMinor = "rgba(32, 32, 32, 1.0)"
view2dAxisX = "rgba(128, 77, 255, 1.0)"
view2dAxisY = "rgba(188, 177, 226, 1.0)"
view2dGeometry = "rgba(220, 220, 240, 1.0)"
consoleInfo = "rgba(255, 255, 255, 1.0)"
consoleWarn = "rgba(255, 220, 120, 1.0)"
consoleError = "rgba(255, 120, 120, 1.0)"
hudText = "rgba(255, 255, 255, 1.0)"
hudTextDim = "rgba(255, 255, 255, 0.55)"
